### PR TITLE
add LuaDist

### PR DESCRIPTION
**Pull request by Akagi201**

### CODE REVIEW

**Comment by LewisJEllis** [comment]
LuaRocks is more widely used and has a relatively large community effort behind it compared to LuaDist which is, by comparison, falling behind. As a result, in keeping with the [guidelines](https://github.com/LewisJEllis/awesome-lua/blob/master/contributing.md) and avoiding listing things just because they exist, I made an intentional decision last year to omit it. Nothing much has changed in the world of LuaDist since thne, so I will stand by that decision.

**Comment by Akagi201** [comment]
I don't agree with you. I think the design of LuaDist is much better than luarocks. I will write a awesome-lua by myself to put LuaDist in it.

**Comment by LewisJEllis** [comment]
For all I know, maybe it is; I haven't studied the internals or caveats of each one enough to have an opinion, so I'm interested to hear why you think its design is so much better. @Tieske, being a contributor to LuaRocks, might have a relevant opinion if he wishes to share it.

Judgments of design aside, here are my judgments of adoption and my reasons for preferring LuaRocks:
1) Package maintainers have a hard time keeping their packages up to date on LuaDist. Many packages on LuaDist are *years* out of date, and LuaDist effectively has no sense of versioning. LuaRocks has no such problem and allows developers to make an account by which to manage their packages, much like npm or pypi.
2) Numbers. Activity on the [LuaRocks mailing list](http://sourceforge.net/p/luarocks/mailman/luarocks-developers/) is orders of magnitude greater than that of the [LuaDist mailing list](https://groups.google.com/forum/#!forum/luadist), and the LuaRocks repository has seen much more development recently. LuaRocks has more thorough documentation and examples, and ~900 packages available to LuaDist's ~300 (and that 300 number hasn't moved in 2 years). I don't know what LuaDist's download numbers are like, but I doubt they compare to the 5-10k/day of LuaRocks.
3) Backing by major projects. Kong, OpenResty, Lapis/MoonScript/leafo, LOVE OlivineLabs, all use or integrate well with LuaRocks.

If someone wants the most up-to-date version of a particular package, they should be able to find it on LuaRocks, but if LuaDist has it at all it will likely be out of date. I consider that to be the bottom line since the stated purpose of this list is to let people find "the most up-to-date practices" and "the ways people are actually doing things and the packages people are actually using."

**Comment by Tieske** [comment]
They are different. LuaRocks has a drawback that it compiles and installs the bindings only, not the core package. LuaDist does both. (obviously for pure Lua modules that doesn't apply)
So installing LuaSec with LuaRocks requires you to first get the binaries and development files for OpenSSL. Where LuaDist includes it all. This is mainly a drawback for Windows users. Especially on unixes most users are capable of installing the dependencies. On Windows this is a showstopper for the average user.

Then again; LuaDist does its thing using cmake. Relying on the LuaDist maintainer to update all the packages and write cmake files for them. This causes the issue discussed above; lagging releases.

A while ago (Lua Workshop in Toulouse, 2013 iirc) there was some discussion on making the manifest files compatible with each other, so a single Lua installation could be used and both LuaRocks and LuaDist could be used to install and remove modules and be aware of each others modules. But I've seen little progress on this lately.

**Pull request closed without merging**
