### PR TITLE
Add more game engines

### PR DESCRIPTION
**Pull request by last-khajiit**

### CODE REVIEW

**Comment by last-khajiit** [comment]
Hello, any feedback?

**Comment by LewisJEllis** [comment]
I don't want to add Agen; one of the authors states [here](http://www.2dengine.com/forum/viewtopic.php?f=2&t=849) that they consider Love2d to be a better and more mature option, and they're only continuing to use it due to existing code and cost of migration.

EGSL hasn't been updated in 3 years and doesn't seem to be widely used in the way that the other game engines on the list are.

I'll take Spring RTS, but I'd like a more concise/to-the-point description, something like:
Spring - Open-source 3D RTS game engine which uses Lua for scripting and customization.

**Comment by last-khajiit** [comment]
well, I agree with you, so what will be better - I will fix my changes according your notes or we will close this PR and you will commit only Spring?

**Comment by LewisJEllis** [comment]
You can just update this PR and I'll merge it when ready.

**Comment by last-khajiit** [comment]
Ok, I fixed it. 
Plese, check it

**Comment by LewisJEllis** [comment]
Looks good, but can you squash into one commit to keep the history clean? If you're not familiar, [this](http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit) will walk you through it.

**Comment by last-khajiit** [comment]
Hi, there are a lot of conflicts now, so I'll close this PR

**Pull request closed without merging**
