### PR TITLE
Added Luerl - An implementation of Lua in clean Erlang/OTP

### PR DESCRIPTION
**Pull request by erlmachinedev**
Added [Luerl](https://github.com/rvirding/luerl) - clean Erlang/OTP implementation of Lua language

### CODE REVIEW

**Comment by erlmachinedev** [comment]
Is this repo under support? I guess it's better to specify the status under Readme section. To avoid confusing of new contributors who tend to support (see no activity here)

**Comment by JaredSartin** [comment]
Seems just straight up abandoned. I have a for that has all the PRs added. It’s not the go to, but it’s something?

**Comment by joeljuca** [comment]
I was going to open a PR to suggest adding Luerl to the implementation lists, but then I found this one.

Luerl is not abandoned. In fact, it seems to be quite an active project for [R. Virding](https://twitter.com/rvirding) (Luerl, Erlang, LFE...). I've attended some events in which he spoke about it with much enthusiasm. And, I've just checked, there was some relevant pretty recent activity in the repository (aka.: commits made last week).

This @erlmachinedev's PR has been hanging for almost two years. Maybe it's time to hit the Merge btn. 😅

**Comment by erlmachinedev** [comment]
> I was going to open a PR to suggest adding Luerl to the implementation lists, but then I found this one.
> 
> Luerl is not abandoned. In fact, it seems to be quite an active project for [R. Virding](https://twitter.com/rvirding) (Luerl, Erlang, LFE...). I've attended some events in which he spoke about it with much enthusiasm. And, I've just checked, there was some relevant pretty recent activity in the repository (aka.: commits made last week).
> 
> This @erlmachinedev's PR has been hanging for almost two years. Maybe it's time to hit the Merge btn. 😅

Hi, I didn't say that Luerl is abandoned one, I meant exactly this repo (LewisJEllis). There is two years between the PR request and the last comment which we can see.

I don't know the status of the repo, so I probably will close the PR as such (see no reason for this)

**Comment by erlmachinedev** [comment]
The owner doesn't respond  after 2 years (the PR is outdated)

**Pull request closed without merging**
